### ISSUE TITLE
VSCode

### ISSUE THREAD

**Issue by noslouch** [oligriffiths/emberconf-broccoli-workshop#1]
For those of us who do not use VSCode, can you give a little info as to why it is suggested for this training?

Are there key features or tools that will improve our learning? Some killer debugging feature that VSCode provides that is applicable here? 

There’s only a few days between now and Monday, so if there’s a new IDE we should get up to speed on, I’d like to know what areas are most relevant.

**Comment by oligriffiths** [comment]
Yup, the repo is just setup to allow interactive debugging in vs code by default. 
It’s not 100% necessary, just helps you learn if you can set breakpoints and step through things. Don’t worry if you’d rather use whatever you’re used to, it’s not a blocker at all. 
Looking forward to meeting you.

**Comment by oligriffiths** [comment]
Will update the readme

**Comment by noslouch** [comment]
Cool! Thanks for clarifying. See you on Monday
